name: kma
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  http: ^1.1.0
  intl: ^0.18.1
  xml:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
